#!/usr/bin/zsh

NO_COLOR=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

SRC='./src'
OUT='./depmanager'

SEPARATOR="###################################################"
FILES=(
  header
  vars
  utils/print
  utils/helpers
  utils/string
  utils/array
  utils/table
  utils/functions
  managers/apt
  managers/node
  main
)

function build {
  local out=""
  local content=""
  local i=0

  echo ${BLUE}Building ${CYAN}$OUT ${BLUE}from ${CYAN}$SRC${NO_COLOR}

  for file in "${FILES[@]}"; do
    # Read file
    content=$(cat $SRC/$file.sh)

    # Remove 1st line (shebang) of non-first files
    if [[ "$i" != 0 ]]; then
      content=$(echo $content | sed 1d)
    fi

    # Remove leading newlines
    content=$(echo $content | sed -e '/./,$!d')


    if [[ "$i" != 0 ]]; then
      content="$SEPARATOR\n# ${file}\n$SEPARATOR\n\n$content"
    fi

    # Append to output
    out="$out$content\n\n"

    i=$((i+1))
  done

  echo $out > $OUT

  echo ${GREEN}Build complete${NO_COLOR}
}

build

