#!/bin/bash
#
# Dependencies managment
# Author: Romain TRUCHI (https://github.com/truchi)
#
# # depmanager
#
# Checks, diffs, installs or updates your dependencies.
# System, NodeJS, Rust.
#
# # Usage
#
# $ depmanager check --directory ~/my/dir --node ~/my/node.csv
#
# # Configuration
#
# `$DEPMANAGER_DIR="/path/to/your/dir"` # No trailing slash
# Defaults to "$HOME/.config/depmanager"

###################################################
# vars
###################################################

SYSTEM_MANAGERS=(apt yum pacman)
NON_SYSTEM_MANAGERS=(node rust)
MANAGERS=("${SYSTEM_MANAGERS[@]}" "${NON_SYSTEM_MANAGERS[@]}")

declare -A DEFAULT
DEFAULT[dir]="$HOME/.config/depmanager"
for manager in "${MANAGERS[@]}"; do
  DEFAULT[$manager]="$manager.csv"
done

declare -A ARG
for manager in "${MANAGERS[@]}"; do
  ARG[$manager]=
done

declare -A FOUND
for manager in "${MANAGERS[@]}"; do
  FOUND[$manager]=
done

declare -A DETECT
for manager in "${MANAGERS[@]}"; do
  DETECT[$manager]=
done

declare -A BYPASS
for manager in "${MANAGERS[@]}"; do
  BYPASS[$manager]=false
done

COMMAND=
DIR=
QUIET=false
YES=false
SIMULATE=false

NO_COLOR=$(tput sgr0)
BOLD=$(tput bold)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

CWD=$(pwd)

###################################################
# utils/print
###################################################

print_date() {
  echo ${MAGENTA}[$(date +"%Y-%m-%d %H:%M:%S")]${NO_COLOR}
}

print_error() {
  echo "$(print_date) ${RED}✗${NO_COLOR} $@"
}

print_warning() {
  $QUIET && return
  echo "$(print_date) ${YELLOW}!${NO_COLOR} $@"
}

print_success() {
  $QUIET && return
  echo "$(print_date) ${GREEN}✔${NO_COLOR} $@"
}

print_info() {
  $QUIET && return
  echo "$(print_date) ${BLUE}${BOLD}i${NO_COLOR} $@"
}

print_confirm() {
  # Auto confirm if flag is given
  $YES && return

  # Prompt confirmation message
  local message="$(print_date) ${YELLOW}${BOLD}?${NO_COLOR} ${BOLD}$1${NO_COLOR} ${YELLOW}(Y)${NO_COLOR}"
  read -p "$message " -n 1 -r

  # Carriage return if user did not press enter
  [[ ! "$REPLY" =~ ^$ ]] && echo

  # Accepts <Enter>, Y or y
  [[ "$REPLY" =~ ^[Yy]$ || "$REPLY" =~ ^$ ]]
}

print_version() {
  echo "${YELLOW}v0.0.1${NO_COLOR}"
}

print_summary () {
  echo "${BOLD}${GREEN}depmanager${NO_COLOR} $(print_version)
${MAGENTA}https://github.com/truchi/depmanager${NO_COLOR}"
}

print_help() {
  local command=$(basename $0)

  echo "${BOLD}${BLUE}Usage:${NO_COLOR}
  ${BOLD}${GREEN}$command${NO_COLOR} [-h|--version]
  ${BOLD}${GREEN}$command${NO_COLOR} [-v|--help]
  ${BOLD}${GREEN}$command${NO_COLOR} <command> [options]

${BOLD}${BLUE}Description:${NO_COLOR}
  ${WHITE}Manages your dependencies.

  List packages you depend on in CSV files (system.csv, node.csv, rust.csv).
  Export \$DEPMANAGER_DIR (containing these files) environment variable (defaults to \$HOME/.config/depmanager).${NO_COLOR}

${BOLD}${BLUE}Commands:${NO_COLOR}
  c${WHITE},${NO_COLOR} check                       ${WHITE}Produces a report with regard to the CSV files${NO_COLOR}
  d${WHITE},${NO_COLOR} diff                        ${WHITE}List installed packages yet not in the CSV files${NO_COLOR}
  i${WHITE},${NO_COLOR} install                     ${WHITE}Installs packages in the CSV files${NO_COLOR}
  u${WHITE},${NO_COLOR} update                      ${WHITE}Updates packages in the CSV files${NO_COLOR}

${BOLD}${BLUE}Options:${NO_COLOR}
  -a${WHITE},${NO_COLOR} --apt <path|url|false>     ${WHITE}Blah${NO_COLOR}
  -y${WHITE},${NO_COLOR} --yum <path|url|false>     ${WHITE}Blah${NO_COLOR}
  -p${WHITE},${NO_COLOR} --pacman <path|url|false>  ${WHITE}Blah${NO_COLOR}
  -n${WHITE},${NO_COLOR} --node <path|url|false>    ${WHITE}Blah${NO_COLOR}
  -r${WHITE},${NO_COLOR} --rust <path|url|false>    ${WHITE}Blah${NO_COLOR}
  -Q${WHITE},${NO_COLOR} --quiet                    ${WHITE}Blah${NO_COLOR}
  -Y${WHITE},${NO_COLOR} --yes                      ${WHITE}Blah${NO_COLOR}
  -S${WHITE},${NO_COLOR} --simulate                 ${WHITE}Blah${NO_COLOR}

${BOLD}${BLUE}Links:${NO_COLOR}
  ${WHITE}- Repository${NO_COLOR}             ${MAGENTA}https://github.com/truchi/depmanager${NO_COLOR}
  ${WHITE}- Website${NO_COLOR}                ${MAGENTA}https://github.com/truchi/depmanager${NO_COLOR}
  ${WHITE}- Documentation${NO_COLOR}          ${MAGENTA}https://github.com/truchi/depmanager${NO_COLOR}
"
}

print_pre_proceed_message () {
  for manager in "${MANAGERS[@]}"; do
    local file="${ARG[$manager]}"
    local bypass="${BYPASS[$manager]}"
    local found="${FOUND[$manager]}"

    # Ignore system manager which are not detected on user's system
    is_system_manager "$manager" && [[ "${DETECT[$manager]}" != true ]] && continue

    # Make message according to bypass & found
    local message="${BOLD}$manager${NO_COLOR}: "
    if   $bypass; then message="$message bypassed"
    elif $found ; then message="$message ${GREEN}✔${NO_COLOR} ($file)"
    else               message="$message ${RED}✗${NO_COLOR} ($file)"
    fi

    if   $bypass; then print_info    $message
    elif $found ; then print_success $message
    else               print_warning $message
    fi
  done
}

###################################################
# utils/helpers
###################################################

#
# Returns true if $1 starts with /, false otherwise
#
is_absolute() {
  [[ "$1" =~ / ]]
}

#
# Returns true if $1 starts with https?://, false otherwise
#
is_url() {
  [[ "$1" =~ https?:// ]]
}

#
# Returns true is $1 is set, false otherwise
#
is_set() {
  [[ ! -z "$1" ]]
}

#
# Returns true if file $1 exists, false otherwise
#
file_exists() {
  [[ -f "$1" ]]
}

#
# Returns true if url $1 exists, false otherwise
#
url_exists() {
  wget -q --spider "$1"
}

#
# Returns true if $1 is found on the system, false otherwise
#
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

#
# Returns true if $1 is in `SYSTEM_MANAGERS`, false otherwise
#
is_system_manager() {
  [[ " ${SYSTEM_MANAGERS[@]} " =~ " $1 " ]]
}

###################################################
# utils/functions
###################################################

#
# Sets `DIR` according to (in this precedence order):
# - env variable (relative to home)
# - default path
#
get_dir() {
  local dir=""

  # If env variable is defined
  if is_set "$DEPMANAGER_DIR"; then
    # Use user's dir
    dir="$DEPMANAGER_DIR"

    # Relative to home
    ! is_absolute "$dir" && dir="$HOME/$dir"
  else
    # Use default dir
    dir="${DEFAULT[dir]}"
  fi

  ARG[dir]="$dir"
}

#
# Sets `ARG[$1]` according to (in this precedence order):
# - cli arg          (relative to current workin directory)
# - default variable (relative to `DIR`)
# Assumes `CWD` is set
#
make_path() {
  local manager="$1"
  local file=""

  # If file is given in args
  if is_set "${ARG[$manager]}"; then
    # Use file arg
    file="${ARG[$manager]}"

    # Relative to current working dir
    ! is_absolute "$file" && ! is_url "$file" && file="$CWD/$file"
  else
    # Use default file, relative to ARG[dir]
    file="${ARG[dir]}/${DEFAULT[$manager]}"
  fi

  ARG[$manager]="$file"
}

#
# Sets `FOUND[$1]` to true if ${ARG[$1]} exists (file/url), to false otherwise
# Returns true in this case, false otherwise
#
check_file() {
  local manager="$1"
  local file="${ARG[$manager]}"

  # If already found, do not try to find again
  if is_set "${FOUND[$manager]}";then
    "${FOUND[$manager]}"
    return
  fi

  # Check for existence of file/url
  if (is_url "$file" && url_exists "$file") || file_exists "$file"; then
    FOUND[$manager]=true
    true
  else
    FOUND[$manager]=false
    false
  fi
}

#
# Sets `DETECT$[$1]` to true if the manager is found on the system, to false otherwise
# Returns true in this case, false otherwise
# Does not detect twice, reuses `DETECT$[$manager]`
#
detect_manager() {
  local manager="$1"

  # If already detected, do not try to detect again
  if is_set "${DETECT[$manager]}"; then
    "${DETECT[$manager]}"
    return
  fi

  # Detection
  if command_exists "${manager}_detect" && ${manager}_detect; then
    DETECT[$manager]=true
    true
  else
    DETECT[$manager]=false
    false
  fi
}

###################################################
# managers/apt
###################################################

#
# Returns true if apt is found on the system, false otherwise
#
apt_detect() {
  if command_exists apt; then
    return 0
  else
    return 1
  fi
}

###################################################
# main
###################################################

#
# Parses args, filling the appropriate global variables
#
parse_args() {
  # Print summary, version and help
  if [[ $# == 0 ]]; then
    print_summary
    echo
    print_help
    exit
  elif [[ $# == 1 ]]; then
    if [[ "$1" == "--version" || "$1" == "-v" ]]; then
      print_version
      exit
    elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
      print_help
      exit
    fi
  fi

  # Get command
  if [[ "$1" == "check" || "$1" == "c" ]]; then
    COMMAND="check"
  elif [[ "$1" == "diff" || "$1" == "d" ]]; then
    COMMAND="diff"
  elif [[ "$1" == "install" || "$1" == "i" ]]; then
    COMMAND="install"
  elif [[ "$1" == "update" || "$1" == "u" ]]; then
    COMMAND="update"
  else
    print_error Unknown command: $1
    exit
  fi

  # Get options
  while [[ $# -gt 1 ]]; do
    case "$2" in
      -a|--apt)
        ARG[apt]="$3"; shift; shift;;
      -y|--yum)
        ARG[yum]="$3"; shift; shift;;
      -p|--pacman)
        ARG[pacman]="$3"; shift; shift;;
      -n|--node)
        ARG[node]="$3"; shift; shift;;
      -r|--rust)
        ARG[rust]="$3"; shift; shift;;
      -Q|--quiet)
        QUIET=true; shift;;
      -Y|--yes)
        YES=true; shift;;
      -S|--simulate)
        SIMULATE=true; shift;;
      -*)
        if [[ "$2" = "-" ]]; then
          print_error "There might be an error in your command, found a lone '-'"
          exit
        fi

        local flags="${2:1}"
        local non_flags=$(echo "$flags" | sed 's/[QYS]//g')

        [[ "$flags" == *"Q"* ]] && QUIET=true
        [[ "$flags" == *"Y"* ]] && YES=true
        [[ "$flags" == *"S"* ]] && SIMULATE=true

        if is_set "$non_flags"; then
          print_error "Unknown flags: ${BOLD}$non_flags${NO_COLOR}"
          exit
        fi

        shift;;
      *)
        print_error "Unknown option: ${BOLD}$2${NO_COLOR}"
        exit
    esac
  done
}

proceed() {
  for manager in "${MANAGERS[@]}"; do
    echo manager:$manager
  done
}

#
# Main
# Parses arguments, resolves files, run specified command
#
main() {
  parse_args $@
  get_dir
  print_info "${BOLD}Depmanager directory${NO_COLOR}: ${ARG[dir]}"

  for manager in "${MANAGERS[@]}"; do
    if [[ "${ARG[$manager]}" = "false" ]]; then
      BYPASS[$manager]=true
    else
      make_path "$manager"
      check_file "$manager"
    fi

    is_system_manager $manager && detect_manager "$manager"
  done

  print_pre_proceed_message

  local confirm_message="Proceed for $COMMAND?"
  $SIMULATE && confirm_message="Simulate $COMMAND?"

  if print_confirm "$confirm_message"; then
    print_info Go!
    proceed
  else
    print_info Bye!
    exit
  fi
}

# Run
main $@


