#!/usr/bin/zsh

SRC='./src'

NO_COLOR=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

function watch {
  clear
  ./build.zsh
  echo ${BLUE}Watching ${CYAN}$SRC${NO_COLOR}

  while inotifywait -qq -e modify $SRC; do
    clear
    echo ${YELLOW}Detected changes ${MAGENTA}$(date)${NO_COLOR}
    ./build.zsh
    echo ${BLUE}Watching ${CYAN}$SRC${NO_COLOR}
  done
}

watch

